---
- name: DEPLOY AS3 DECLARATION
  hosts: localhost
  connection: local
  gather_facts: no

  vars:

    uri_method: POST

  vars_files:
    - /mnt/c/projects/creds/bigip_creds.yaml

  tasks:

  - name: AS3 Declaration
    uri:
      url: https://52.14.169.147/mgmt/shared/appsvcs/declare
      user: "{{ bigip_user }}"
      password: "{{ bigip_pass }}"
      method: "{{ uri_method }}"
      body: "{{ lookup('file','as3-declaration.json') }}"
      force_basic_auth: yes
      status_code: 200
      body_format: json
      validate_certs: no